### ISSUE TITLE
`cbor-diag` overflow

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-rs#116]
The CLI returns

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/fmorency/.cargo/registry/src/github.com-1ecc6299db9ec823/cbor-diag-0.1.8/src/encode/diag.rs:42:42
```

when running

`many message --server https://alberto.app/api ledger.list '{}'`

Investigate.

**Comment by fmorency** [comment]
The CBOR produced by the server is okay, it can be decoded by cbor.me as well as by https://cbor.nemo157.com/, which is the browser-based tool based on `cbor-diag`.

After some investigation, I found that this issue is happening only when compiling in `debug` and NOT when compiling in `release`.

**Comment by fmorency** [comment]
I can reproduce the crash with

```
{
    0: h'0128bf0000002c',
    1: 1(1654099789_2),
    2: {0: [4, 0]},
}
```

which translate to

```
$ echo a300470128bf0000002c01c11a62978f4d02a100820400 | ./target/debug/cbor-diag --to diag
thread 'main' panicked at 'attempt to subtract with overflow', src/encode/diag.rs:42:42
```

**Comment by fmorency** [comment]
See https://github.com/Nemo157/cbor-diag-rs/issues/113
